card_dict = {("graphics/clubs/card_clubs_02.png",
"graphics/diamonds/card_diamonds_02.png",
"graphics/hearts/card_hearts_02.png",
"graphics/spades/card_spades_02.png"): 2, 
("graphics/clubs/card_clubs_03.png",
"graphics/diamonds/card_diamonds_03.png",
"graphics/hearts/card_hearts_03.png",
"graphics/spades/card_spades_03.png"): 3,
("graphics/clubs/card_clubs_04.png",
"graphics/diamonds/card_diamonds_04.png",
"graphics/hearts/card_hearts_04.png",
"graphics/spades/card_spades_04.png"): 4,
("graphics/clubs/card_clubs_05.png", 
"graphics/diamonds/card_diamonds_05.png",
"graphics/hearts/card_hearts_05.png",
"graphics/spades/card_spades_05.png"): 5,
("graphics/clubs/card_clubs_06.png",
"graphics/diamonds/card_diamonds_06.png",
"graphics/hearts/card_hearts_06.png",
"graphics/spades/card_spades_06.png"): 6,
("graphics/clubs/card_clubs_07.png",
"graphics/diamonds/card_diamonds_07.png",
"graphics/hearts/card_hearts_07.png",
"graphics/spades/card_spades_07.png"): 7,
("graphics/clubs/card_clubs_08.png",
"graphics/diamonds/card_diamonds_08.png",
"graphics/hearts/card_hearts_08.png",
"graphics/spades/card_spades_08.png"): 8,
("graphics/clubs/card_clubs_09.png",
"graphics/diamonds/card_diamonds_09.png",
"graphics/hearts/card_hearts_09.png",
"graphics/spades/card_spades_09.png"): 9,
("graphics/clubs/card_clubs_10.png",
"graphics/diamonds/card_diamonds_10.png",
"graphics/hearts/card_hearts_10.png",
"graphics/spades/card_spades_10.png",
"graphics/clubs/card_clubs_J.png",
"graphics/clubs/card_clubs_K.png",
"graphics/clubs/card_clubs_Q.png",
"graphics/diamonds/card_diamonds_J.png",
"graphics/diamonds/card_diamonds_K.png",
"graphics/diamonds/card_diamonds_Q.png",
"graphics/hearts/card_hearts_J.png",
"graphics/hearts/card_hearts_K.png",
"graphics/hearts/card_hearts_Q.png",
"graphics/spades/card_spades_J.png",
"graphics/spades/card_spades_K.png",
"graphics/spades/card_spades_Q.png"): 10,
("graphics/clubs/card_clubs_A.png",
"graphics/diamonds/card_diamonds_A.png",
"graphics/hearts/card_hearts_A.png",
"graphics/spades/card_spades_A.png"): [11, 1]}